/// <reference types="node" />
import { Network, Payment, Psbt, Signer, Transaction } from 'bitcoinjs-lib';
import { PsbtInputExtended, PsbtOutputExtended, UpdateInput } from '../interfaces/Tap.js';
import { TransactionType } from '../enums/TransactionType.js';
import { IFundingTransactionParameters, ITransactionParameters } from '../interfaces/ITransactionParameters.js';
import { Address } from '@btc-vision/bsi-binary';
import { UTXO } from '../../utxo/interfaces/IUTXO.js';
export declare abstract class TransactionBuilder<T extends TransactionType> {
    protected static readonly LOCK_LEAF_SCRIPT: Buffer;
    protected static readonly MINIMUM_DUST: bigint;
    abstract readonly type: T;
    readonly logColor: string;
    transactionFee: bigint;
    protected readonly transaction: Psbt;
    protected readonly inputs: PsbtInputExtended[];
    protected readonly updateInputs: UpdateInput[];
    protected readonly outputs: PsbtOutputExtended[];
    protected feeOutput: PsbtOutputExtended | null;
    protected signed: boolean;
    protected tapData: Payment | null;
    protected scriptData: Payment | null;
    protected totalInputAmount: bigint;
    protected readonly signer: Signer;
    protected readonly network: Network;
    protected readonly feeRate: number;
    protected readonly priorityFee: bigint;
    protected utxos: UTXO[];
    protected to: Address;
    protected from: Address;
    private _maximumFeeRate;
    protected constructor(parameters: ITransactionParameters);
    getFundingTransactionParameters(): IFundingTransactionParameters;
    setDestinationAddress(address: Address): void;
    setMaximumFeeRate(feeRate: number): void;
    signTransaction(): Transaction;
    getTransaction(): Transaction;
    getScriptAddress(): string;
    getTapAddress(): string;
    addInput(input: PsbtInputExtended): void;
    addOutput(output: PsbtOutputExtended): void;
    protected addRefundOutput(amountSpent: bigint): void;
    protected getTransactionOPNetFee(): bigint;
    protected calculateTotalUTXOAmount(): bigint;
    protected calculateTotalVOutAmount(): bigint;
    protected addInputsFromUTXO(): void;
    protected witnessStackToScriptWitness(witness: Buffer[]): Buffer;
    protected internalInit(): void;
    protected abstract buildTransaction(): void;
    protected generateScriptAddress(): Payment;
    protected generateTapData(): Payment;
    protected updateInput(input: UpdateInput): void;
    protected getWitness(): Buffer;
    protected getTapOutput(): Buffer;
    protected getInputs(): PsbtInputExtended[];
    protected getOutputs(): PsbtOutputExtended[];
    protected verifyUTXOValidity(): void;
    protected setFeeOutput(output: PsbtOutputExtended): void;
    protected abstract getSignerKey(): Signer;
    protected internalPubKeyToXOnly(): Buffer;
    protected signInputs(transaction: Psbt): void;
    private internalBuildTransaction;
    private estimateTransactionFees;
}
