/// <reference types="node" />
import { Network, Psbt, Signer, Transaction } from 'bitcoinjs-lib';
import { PsbtInputExtended, PsbtOutputExtended, UpdateInput } from '../interfaces/Tap.js';
import { TransactionType } from '../enums/TransactionType.js';
import { IFundingTransactionParameters, ITransactionParameters } from '../interfaces/ITransactionParameters.js';
import { Address } from '@btc-vision/bsi-binary';
import { UTXO } from '../../utxo/interfaces/IUTXO.js';
import { ECPairInterface } from 'ecpair';
import { TweakedTransaction } from '../shared/TweakedTransaction.js';
export declare abstract class TransactionBuilder<T extends TransactionType> extends TweakedTransaction {
    static readonly LOCK_LEAF_SCRIPT: Buffer;
    static readonly MINIMUM_DUST: bigint;
    abstract readonly type: T;
    readonly logColor: string;
    overflowFees: bigint;
    transactionFee: bigint;
    estimatedFees: bigint;
    protected transaction: Psbt;
    protected readonly updateInputs: UpdateInput[];
    protected readonly outputs: PsbtOutputExtended[];
    protected feeOutput: PsbtOutputExtended | null;
    protected totalInputAmount: bigint;
    protected readonly signer: Signer;
    protected readonly network: Network;
    protected readonly feeRate: number;
    protected priorityFee: bigint;
    protected utxos: UTXO[];
    protected to: Address | undefined;
    protected from: Address;
    protected _maximumFeeRate: number;
    protected constructor(parameters: ITransactionParameters);
    static getFrom(from: string | undefined, keypair: ECPairInterface, network: Network): Address;
    static witnessStackToScriptWitness(witness: Buffer[]): Buffer;
    getFundingTransactionParameters(): Promise<IFundingTransactionParameters>;
    setDestinationAddress(address: Address): void;
    setMaximumFeeRate(feeRate: number): void;
    signTransaction(): Promise<Transaction>;
    generateTransactionMinimalSignatures(): Promise<void>;
    signPSBT(): Promise<Psbt>;
    addInput(input: PsbtInputExtended): void;
    addOutput(output: PsbtOutputExtended): void;
    toAddress(): string | undefined;
    address(): Address | undefined;
    estimateTransactionFees(): Promise<bigint>;
    rebuildFromBase64(base64: string): Promise<Psbt>;
    setPSBT(psbt: Psbt): void;
    protected addRefundOutput(amountSpent: bigint): Promise<void>;
    protected addValueToToOutput(value: number | bigint): void;
    protected getTransactionOPNetFee(): bigint;
    protected calculateTotalUTXOAmount(): bigint;
    protected calculateTotalVOutAmount(): bigint;
    protected addInputsFromUTXO(): void;
    protected internalInit(): void;
    protected abstract buildTransaction(): Promise<void>;
    protected updateInput(input: UpdateInput): void;
    protected getWitness(): Buffer;
    protected getTapOutput(): Buffer;
    protected getInputs(): PsbtInputExtended[];
    protected getOutputs(): PsbtOutputExtended[];
    protected verifyUTXOValidity(): void;
    protected setFeeOutput(output: PsbtOutputExtended): Promise<void>;
    protected internalBuildTransaction(transaction: Psbt): Promise<boolean>;
}
