export enum WalletNetworks {
    Mainnet = 'mainnet',
    Testnet = 'testnet',
    OpnetTestnet = 'opnetTestnet',
    Regtest = 'regtest',
}

export enum UnisatChainType {
    BITCOIN_MAINNET = 'BITCOIN_MAINNET',
    BITCOIN_TESTNET = 'BITCOIN_TESTNET',
    BITCOIN_TESTNET4 = 'BITCOIN_TESTNET4',
    BITCOIN_REGTEST = 'BITCOIN_REGTEST',
    BITCOIN_SIGNET = 'BITCOIN_SIGNET',
    OPNET_TESTNET = 'OPNET_TESTNET',
    FRACTAL_BITCOIN_MAINNET = 'FRACTAL_BITCOIN_MAINNET',
    FRACTAL_BITCOIN_TESTNET = 'FRACTAL_BITCOIN_TESTNET',
    DOGECOIN_MAINNET = 'DOGECOIN_MAINNET',
    DOGECOIN_TESTNET = 'DOGECOIN_TESTNET',
    DOGECOIN_REGTEST = 'DOGECOIN_REGTEST',
    LITECOIN_MAINNET = 'LITECOIN_MAINNET',
    LITECOIN_TESTNET = 'LITECOIN_TESTNET',
    LITECOIN_REGTEST = 'LITECOIN_REGTEST',
    BITCOINCASH_MAINNET = 'BITCOINCASH_MAINNET',
    BITCOINCASH_TESTNET = 'BITCOINCASH_TESTNET',
    BITCOINCASH_REGTEST = 'BITCOINCASH_REGTEST',
    DASH_MAINNET = 'DASH_MAINNET',
    DASH_TESTNET = 'DASH_TESTNET',
    DASH_REGTEST = 'DASH_REGTEST',
}
