export declare enum Consensus {
    Roswell = 0,
    Rachel = 1,
    Kecksburg = 2,
    Phoenix = 3,
    Aurora = 4,
    Rendlesham = 5,
    Lazar = 6,
    ShagHarbor = 7,
    Exeter = 8,
    Stephenville = 9,
    Valensole = 10,
    Socorro = 11,
    Pascagoula = 12,
    Tehran = 13,
    Westall = 14,
    Hopkinsville = 15,
    Belgium = 16,
    Breeze = 17,
    Flatwoods = 18,
    Maury = 20,
    Varginha = 21,
    Trindade = 22,
    Levelland = 23,
    Wanaque = 24,
    Coyame = 25,
    Delphos = 26
}
